### ISSUE TITLE
[r128Sqrt] static_asser on linux for number 741321

### ISSUE THREAD

**Issue by favorart** [fahickman/r128#1]
`bm: r128.h:849: uint64_t r128__udiv128(uint64_t, uint64_t, uint64_t, uint64_t*): Assertion `n3 < d1' failed.`

On windows it works fine and gives the correct answer.
Now, I just comment this line.
Can you explain what problem can it be?

**Comment by fahickman** [comment]
Hi,

Sorry about the bug. That assert definitely should not fire. Can you tell me what compiler and command-line arguments you're using and what value you're passing to r128Sqrt that triggers the assert? That will allow me to try to reproduce the problem.

Thanks.

**Comment by fahickman** [comment]
I've been able to reproduce this now. I don't yet have a fix, but as a temporary workaround, you can put

#define R128_STDC_ONLY

in your implementation file before including r128.h. This will slow some operations down, but will fix the assert until I can find the proper fix.

Thanks.

**Comment by fahickman** [comment]
After further investigation, I believe this assert is caused by this gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81294

I just verified that this bug was fixed in gcc 7.2. So you can either upgrade your gcc to 7.2 or later, or stick with the R128_STDC_ONLY workaround on Linux.

Thank you for reporting this issue.

**Comment by fahickman** [comment]
The assert is verifying that the algorithm is generating the correct results, so there's no working around it.

I downloaded gcc 4.8.5, and with R128_STDC_ONLY set, I get no asserts, and the correct answer, so for the moment, I don't have a solution for you. Sorry. I will keep trying to reproduce the problem, and let you know as soon as I find anything.

**Comment by favorart** [comment]
I was able to create a working example with the error appearing
[https://cloud.mail.ru/public/88Cr/f2rfSNEoW](url)

**Comment by fahickman** [comment]
Thank you very much for the example, I was able to reproduce the assert with it. Sorry it took so long to get back to you, but I wanted to spend the time to make sure I understood the problem fully. After studying the problem, I believe that the assert is incorrect, in that the case where n2 == d1 is valid and must be handled.

Can you please check the latest r128.h and see if it fixes the problem for you?

**Comment by favorart** [comment]
I checked is out. As I see now it is fine.
Thank you
