### ISSUE TITLE
May be a bug for operator divide

### ISSUE THREAD

**Issue by ZhongliangGong** [fahickman/r128#14]
Running the following code, c will get -1 rather than R128_max:
R128 a = -1;
a.lo = 1; //NOTE: without this line, the result will be right
R128 b = -5.4210108624275222e-20;
R128 c = a / b;

**Comment by ZhongliangGong** [comment]
Another testcase:
R128 a, b;
a.lo = 18446744073709550558;
a.hi = 1;
b.lo = 2;
b.hi = 0;
a / b will return a wrong number.
When the overflow happens, I think return an R128_max/R128_min instead of an undefined value is more acceptable.
Thank you for your great job on this awesome fixed-point library. 
It benefits our work much.

**Comment by fahickman** [comment]
I had to think about this for a good while, and I think I will leave this as is.

The difficulty is that fixed point has no special values, like NaN or Inf, as floating point does. R128_min/max are not special values, and are therefore are just as wrong as any other value.

Some possibilities are to add a checked divide function, or a #define to control domain error behavior, or a special global such as errno, or a user-supplied callback. There are lots of tradeoffs involved in all of these.

However, if someone really has a compelling case for one or more of those options, they can reopen this issue, and I'll be happy to consider it.

**Comment by ZhongliangGong** [comment]
Thank you for your reply. 
You are right, in my case, I just need a clear signal to let me know that the result is overflow.
I'm developing a fast geometry boolean algorithm, and this is a very common situation.
Although R128_max / R128_min is as wrong as other values, but it doesn't confuse the trend of the algorithm calculation，it can be considered as precision loss just as what float point format done to large numbers. 
And R128_max/R128_min can also be used as a clue to remind the caller overflow may be happens. 
I think define a global NaN is a good idea, just occupy one position, and all problems are solved.
