### ISSUE TITLE
Precision for modulo

### ISSUE THREAD

**Issue by sturmE** [fahickman/r128#3]
Hello, 

I'm trying to take remainders then clamp to zero if they are within a certain epsilon value. The issue I'm running into is the variability of the error when doing modulo of different values that should be zero.

Example:

```
char result[32];
const char* strA = "100000";
const char* strB = "0.001";
R128 a, b, c;
r128FromString(&a, strA, nullptr);
r128FromString(&b, strB, nullptr);
c = (a - b) % b;
r128ToString(result, 32, &c);
```
result -> "0.00000000000333934269"

But if I do:

```
strA = "10";
strB = "0.1";
```
result -> "0.00000000000000000325"

Is this expected behavior?

**Comment by fahickman** [comment]
I think the issue that you're having here is simply that 0.1 and 0.001 are not exactly representable in binary, no matter how many bits of precision you have (0.1 decimal is the infinitely repeating binary number 0.0001100110011...). If you use a number that can be represented in binary, like 0.125 or 0.0009765625, your modulus will be exactly zero. So your result being non-zero is expected, as is the magnitude of the error being proportional to the difference in magnitudes of the two numbers.

If you're looking for an epsilon to use when comparing two results, generally you want to scale it based on the magnitudes of the comparands. See for example: http://realtimecollisiondetection.net/blog/?p=89 (the title mentions floating-point, but it's really a more general significant figures issue.)

If you do need the modulus to be zero in all cases, then you'll need to use an arbitrary-precision math library (or a rational number library) instead.

Hope that helps.

**Comment by fahickman** [comment]
It's been a while, so I'm going to close this. Please reopen it if you still need help.

Thanks!
