### ISSUE TITLE
It seems r128 is not exact representation of fractional number.

### ISSUE THREAD

**Issue by yihuang** [fahickman/r128#6]
```
#include <stdio.h>

#define R128_IMPLEMENTATION
#include "r128.h"

int main() {
    R128 r;
    char buf[32];
    size_t len;
    r128FromString(&r, "0.1", nullptr);
    len = r128ToString(buf, sizeof(buf)-1, &r);
    buf[len] = '\0';
    printf("%s\n", buf);
}
```

Outputs:
```
0.09999999999999999997
```

Is it expected behaviour?

**Comment by fahickman** [comment]
Yes, this is expected. 0.1 is not exactly representable in binary, no matter how many bits of precision you have. You'd need a rational number or arbitrary precision arithmetic library to represent it exactly.

On an unrelated note, r128ToString follows the same rules as snprintf in that it always null terminates and returns the number of characters that would have been written in the case that the buffer was too small. So it is not necessary to subtract 1 from sizeof(buf) or manually terminate. In fact, writing to buf[len] could cause a crash.
